config/routes.rb
Rails.application.routes.draw do

  get 'floorplans/view'
  resources :floorplans
  
  resources :rooms
	resources :buildings

  get 'welcome/index'
	get 'welcome/about', :as => :about_this_site

  root 'welcome#index'

  get '/floorplans/:floorplan_name' => 'floorplans#show', :as => :floorplan_by_name 
  

  get 'admin' => 'admin#index'

  namespace :admin do
    get 'admin/index'
		get 'rooms/floorplan_filter_options' => 'rooms#floorplan_filter_options'
    resources :buildings
    resources :floorplans do
      post 'add_floor_area' => 'floorplans#add_floor_area'
			post 'update_floor_area/:floor_area_id' => 'floorplans#update_floor_area', :as => 'update_floor_area'
    end
		resources :floor_areas
    resources :rooms do
      post 'add_room_area' => 'rooms#add_room_area'
			post 'update_room_area' => 'rooms#update_room_area'
    end
    resources :rooms
		resources :room_areas
		resources :floorplan_maps
  end
  
  get "/support" => redirect("http://library.duke.edu/support"), :as => :support_home
  get "/featured-story" => redirect("http://library.duke.edu/support/crazy-smart"), :as => :featured_story
  get "/giving-opportunities" => redirect("http://library.duke.edu/support/giving-opportunities"), :as => :giving_opportunities
  get "/friends" => redirect("http://library.duke.edu/support/friends"), :as => :friends_of_libraries
  get "/news" => redirect("http://blogs.library.duke.edu"), :as => :news_and_events
  get "/how-to-give" => redirect("http://library.duke.edu/support/how-give"), :as => :how_to_give
  get "/give-now" => redirect("https://www.gifts.duke.edu/library"), :as => :give_now
  get "/contact" => redirect("http://library.duke.edu/support/contact"), :as => :contact
end

app/views/admin/index.html.erb
<div class="row">
	<div class="col-xs-6 col-md-3 admin-section">
		<a href="<%= url_for(admin_buildings_path) %>">
		<%= image_tag "dul-libraries-profile-google-earth-#{@perkins.name}-ground-level-#{@perkins.image_width}x#{@perkins.image_height}.jpg", 
									alt: "Profile of the #{@perkins.label}",
									class: "img-circle", height: 200, width: 200
									%>
		</a>
		<h4><a href="<%= url_for(admin_buildings_path) %>">Buildings</a></h4>									
	</div>
	<div class="col-xs-6 col-md-3 admin-section">
		<a href="<%= url_for(admin_floorplans_path) %>">
		<%= image_tag "floorplans/floorplanmap/perkins_floor_1_full_size_1.png", 
									alt: "Profile of the #{@perkins.label}",
									class: "img-circle", height: 200, width: 200
									%>
		</a>
		<h4><a href="<%= url_for(admin_floorplans_path) %>">Floorplans</a></h4>										
	</div>
	<div class="col-xs-6 col-md-3 admin-section">
		<a href="<%= url_for(admin_rooms_path) %>">
		<%= image_tag "floorplans/roommockup/bostock_fl01_hively_study_room.jpg", 
									alt: "Profile of the #{@perkins.label}",
									class: "img-circle", height: 200, width: 200
									%>
		</a>
		<h4><a href="<%= url_for(admin_rooms_path) %>">Rooms &amp; Room Areas</a></h4>					
	</div>
	<div class="col-xs-6 col-md-3 admin-section">
		<a href="<%= url_for(admin_buildings_path) %>">
		<%= image_tag "dul-libraries-profile-google-earth-#{@perkins.name}-ground-level-#{@perkins.image_width}x#{@perkins.image_height}.jpg", 
									alt: "Profile of the #{@perkins.label}",
									class: "img-circle", height: 200, width: 200
									%>
		</a>
		<h4>Other Stuff</h4>							
	</div>
</div>