config/routes.rb
Rails.application.routes.draw do

  get 'floorplans/view'
  resources :floorplans
  
  resources :rooms
	resources :buildings

  get 'welcome/index'
	get 'welcome/about', :as => :about_this_site

  root 'welcome#index'

  get '/floorplans/:floorplan_name' => 'floorplans#show', :as => :floorplan_by_name 
  

  get 'admin' => 'admin#index'

  namespace :admin do
    get 'admin/index'
		get 'rooms/floorplan_filter_options' => 'rooms#floorplan_filter_options'
    resources :buildings
    resources :floorplans do
      post 'add_floor_area' => 'floorplans#add_floor_area'
			post 'update_floor_area/:floor_area_id' => 'floorplans#update_floor_area', :as => 'update_floor_area'
    end
		resources :floor_areas
    resources :rooms do
      post 'add_room_area' => 'rooms#add_room_area'
			post 'update_room_area' => 'rooms#update_room_area'
    end
    resources :rooms
		resources :room_areas
		resources :floorplan_maps
  end
  
  get "/support" => redirect("http://library.duke.edu/support"), :as => :support_home
  get "/featured-story" => redirect("http://library.duke.edu/support/crazy-smart"), :as => :featured_story
  get "/giving-opportunities" => redirect("http://library.duke.edu/support/giving-opportunities"), :as => :giving_opportunities
  get "/friends" => redirect("http://library.duke.edu/support/friends"), :as => :friends_of_libraries
  get "/news" => redirect("http://blogs.library.duke.edu"), :as => :news_and_events
  get "/how-to-give" => redirect("http://library.duke.edu/support/how-give"), :as => :how_to_give
  get "/give-now" => redirect("https://www.gifts.duke.edu/library"), :as => :give_now
  get "/contact" => redirect("http://library.duke.edu/support/contact"), :as => :contact
end

app/views/shared/_breadcrumbs.html.erb
<% if @breadcrumbs %>
	<ol class="breadcrumb">
  <% @breadcrumbs[0..-2].each do |txt, path| %>
    <li><%= link_to(h(txt), path) %></li>
  <% end %>
  	<li><%= h(@breadcrumbs.last.first) %></li>
  </ol>
<% end %>

app/views/shared/_carousel.html.erb
<div id="<%= @carousel_div_id %>" class="carousel slide<%= " " + @carousel_classes.join(' ') %>" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  <% for n in 0..(@carousel_items.size - 1) %>
  	<% if @carousel_items[n].has_key? :active and @carousel_items[n][:active] %>
  		<li data-target="#<%= @carousel_div_id %>" data-slide-to="<%= n %>" class="active">
  	<% else %>
  		<li data-target="#<%= @carousel_div_id %>" data-slide-to="<%= n %>">
  	<% end %>
  <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  <% @carousel_items.each do |item| %>
    <div class="item<% if item.has_key? :active and item[:active] %> active<% end %>">
			<%= image_tag item[:image_url], alt: "#{item[:image_alt]}" %>
      <!-- img src="/assets/<%= item[:image_url] %>" alt="<%= item[:image_alt] %>"-->
      <% if item.has_key? :image_caption %>
      <div class="carousel-caption">
        <%= item[:image_caption]%>
      </div>
      <% end %>
    </div>
  <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#<%= @carousel_div_id %>" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#<%= @carousel_div_id %>" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_floors_buildings_menu.html.erb
		<div class="btn-group" role="group" aria-label="...">
			<% if building_list[active_floorplan.building.name][:room_list].count > 0 %>
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
		      <%= active_floorplan.building.label %> Floors
		      <span class="caret"></span>
		    	</button>
		    	<ul class="dropdown-menu" role="menu">
					<% @building_list[active_floorplan.building.name][:room_list].each do |floor| %>
						<li class="<%= active_floorplan.label === floor.label ? "active" : "" %>"><%= link_to floor.label, floorplan_path(:id => floor.id) %></li>
					<% end %>
					</ul>
				</div>
			<% end %>
		
		  <div class="btn-group" role="group">
		    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
		      Library Buildings
		      <span class="caret"></span>
		    </button>
		    <ul class="dropdown-menu" role="menu">
				<% building_list.each do |building, building_info|%>
					<li class="<%= active_building.label === building_info[:label] ? "active" : "" %>">
					<%= link_to building_info[:label], building_path(:id => building_info[:id]) %></a>
					</li>
				<% end %>
		    </ul>
		  </div>
		</div>

app/views/shared/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-sm-1">
				<a href="//library.duke.edu"><img src="<%= asset_path('devillogo-60pct-60.png') %>"/></a>
			</div>
			<div class="col-sm-2">
				<div class="h5">Contact Us</div>
				<p class="small">
					411 Chapel Drive<br />
					Durham, NC 27708
				</p>
				<p class="small">
					(919) 660-5870<br />
					Perkins Library Service Desk
				</p>
			</div>
			<div class="col-sm-4">
				<div class="h5">Services for...</div>
				<ul class="list-inline">
					<li>
						<ul class="list-unstyled small">
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'Faculty Instructors'});" href="http://library.duke.edu/services/faculty">Faculty &amp; Instructors</a></li>
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'Graduate Students'});" href="http://library.duke.edu/services/graduate">Graduate Students</a></li>
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'Undergraduate Students'});" href="http://library.duke.edu/services/undergraduate">Undergraduate Students</a></li>
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'International Students'});" href="http://library.duke.edu/services/international">International Students</a></li>
						</ul>
					</li>
					<li>
						<ul class="list-unstyled small">
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'Alumni'});" href="http://library.duke.edu/services/alumni">Alumni</a></li>
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'Donors'});" href="http://library.duke.edu/services/donors">Donors</a></li>	
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'Visitors'});" href="http://library.duke.edu/services/visitors">Visitors</a></li>								
							<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Services', eventLabel: 'Patrons with Disabilities'});" href="http://library.duke.edu/services/disabilities">Patrons with Disabilities</a></li>	
						</ul>
					</li>
				</ul>
			</div>
			<div class="col-sm-3">
				<div class="socialMediaIconsBig">
					<a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Social', eventLabel: 'Twitter'});" href="https://twitter.com/DukeLibraries" title="Twitter">
						<div class="twitter"></div></a>
					<a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Social', eventLabel: 'Facebook'});" href="https://www.facebook.com/dukelibraries" title="Facebook">
						<div class="facebook"></div></a>
					<a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Social', eventLabel: 'Youtube'});" href="http://www.youtube.com/user/DukeUnivLibraries" title="Youtube">
						<div class="youtube"></div></a>
					<a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Social', eventLabel: 'Flickr'});" href="http://www.flickr.com/photos/dukeunivlibraries/" title="Flickr">
						<div class="flickr"></div></a>
					<a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Social', eventLabel: 'Pinterest'});" href="http://www.pinterest.com/dukelibraries/" title="Pinterest">
						<div class="instagram"></div></a>
					<a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Social', eventLabel: 'RSS'});" href="http://blogs.library.duke.edu/" title="RSS">
						<div class="rss"></div></a>
				</div>
				<ul class="list-unstyled small">
					<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Links', eventLabel: 'Re-use and Attribution'});" href="/about/reuse-attribution">Re-use &amp; Attribution</a> / <a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Links', eventLabel: 'Privacy'});" href="/about/privacy">Privacy</a></li>
					<li><a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Links', eventLabel: 'Support the Libraries'});" href="/support">Support the Libraries</a></li>
				</ul>
				<a onClick="ga('send', 'event', { eventCategory: 'Footer', eventAction: 'Links', eventLabel: 'Creative Commons'});" rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US" ><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" title="This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License" /></a>
			</div>
			<div class="col-sm-2 pull-right">
				<a href="//duke.edu"><img src="<%= asset_path('dukelogo_vert_60pct_140.png') %>"/></a>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_menu.html.erb
	
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header navbar-right">
					<a class="logo navbar-btn pull-left" href="http://dukeforward.duke.edu" title="Duke Forward Home">
          	<img src="<%= asset_path('duke_df_logo_web_white.png') %>" alt="Home">
        	</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--a class="navbar-brand" href="/">Support The Libraries</a-->
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="<%= root_path %>"><strong>Support The Libraries</strong></a></li>
            <li class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About <span class="caret"></span></a>
            	<ul class="dropdown-menu" role="menu">
								<li><a href="<%= support_home_path %>">Transform Lives</a></li>
								<li><a href="<%= featured_story_path %>">Featured Story</a></li>
								<li><a href="<%= giving_opportunities_path %>">Giving Opportunities</a></li>
								<li><a href="<%= friends_of_libraries_path %>">Friends of the Libraries</a></li>
								<li><a href="<%= news_and_events_path %>">News, Events, Exhibits</a></li>
								<li role="separator" class="divider"></li>
								<li><a data-toggle="modal" data-target="#aboutNamingOpsModal" href="#">About This Site...</a></li>
            	</ul>
            </li>
            <li><a href="<%= contact_path %>">Contact</a></li>
          </ul>
	        <form class="navbar-form navbar-right" style="margin-right: 1em;">
	        	<a href="<%= give_now_path %>" target="_blank" class="give-now btn btn-default">Give Now!</a>
	        </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>