config/routes.rb
Rails.application.routes.draw do

  get 'floorplans/view'
  resources :floorplans
  
  resources :rooms
	resources :buildings

  get 'welcome/index'
	get 'welcome/about', :as => :about_this_site

  root 'welcome#index'

  get '/floorplans/:floorplan_name' => 'floorplans#show', :as => :floorplan_by_name 
  

  get 'admin' => 'admin#index'

  namespace :admin do
    get 'admin/index'
		get 'rooms/floorplan_filter_options' => 'rooms#floorplan_filter_options'
    resources :buildings
    resources :floorplans do
      post 'add_floor_area' => 'floorplans#add_floor_area'
			post 'update_floor_area/:floor_area_id' => 'floorplans#update_floor_area', :as => 'update_floor_area'
    end
		resources :floor_areas
    resources :rooms do
      post 'add_room_area' => 'rooms#add_room_area'
			post 'update_room_area' => 'rooms#update_room_area'
    end
    resources :rooms
		resources :room_areas
		resources :floorplan_maps
  end
  
  get "/support" => redirect("http://library.duke.edu/support"), :as => :support_home
  get "/featured-story" => redirect("http://library.duke.edu/support/crazy-smart"), :as => :featured_story
  get "/giving-opportunities" => redirect("http://library.duke.edu/support/giving-opportunities"), :as => :giving_opportunities
  get "/friends" => redirect("http://library.duke.edu/support/friends"), :as => :friends_of_libraries
  get "/news" => redirect("http://blogs.library.duke.edu"), :as => :news_and_events
  get "/how-to-give" => redirect("http://library.duke.edu/support/how-give"), :as => :how_to_give
  get "/give-now" => redirect("https://www.gifts.duke.edu/library"), :as => :give_now
  get "/contact" => redirect("http://library.duke.edu/support/contact"), :as => :contact
end

app/models/building.rb
class Building < ActiveRecord::Base
  cattr_accessor  :image_size
  attr_accessor   :image_height
  attr_accessor   :image_width
  
  @@image_size = {
    'perkins' => { :width => '479', :height => '268' },
    'lilly' => { :width => '524', :height => '268' },
    'rubenstein' => { :width => '513', :height => '268' },
    'bostock' => { :width => '498', :height => '234' },
  }
  
  include    BuildingSize
  has_many   :floorplans, -> { order "label ASC" }
  
  # http://stackoverflow.com/questions/11636541/use-a-scope-by-default-on-a-rails-has-many-relationship
  has_many   :below_ground_floorplans, -> { below_ground }, class_name: "Floorplan"
  has_many   :above_ground_floorplans, -> { above_ground }, class_name: "Floorplan"
  
  after_initialize :init
  
  def init
    self.image_height = Building.image_size[self.name][:height]
    self.image_width =  Building.image_size[self.name][:width]
  end
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < AdminController
  add_breadcrumb 'Buildings', 'admin_buildings_path'
  
  def new
    @building = Building.new
  end
  
  def create
    @building = Building.new(building_params)
  end
  
  def index
    # admin/floorplans
    #set_active_admin_sidebar 'Buildings'
    @buildings = Building.all.order('label')
  end
  
  def edit
    # admin/floorplans/:id
    @building = Building.find(params[:id])
    add_breadcrumb @building.label
  end
  
  private
    def building_params
      params.require(:building).permit(:label, :name, :sublabel)
    end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
	def index
		@buildings = Building.all
	end

  # load the appropriate building, then
  # find the "First Floor" record, and finally
  # redirect to the view of that model object.
	def show
		building = Building.find(params[:id])
		
		# set the default floor, then redirect to the Floorplan controller 
		default_floorplan = building.floorplans.where('label LIKE ?', 'Floor 1%').first
		redirect_to default_floorplan
	end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/admin/buildings/edit.html.erb
<h3>Edit <%= @building.label %></h3>
<%= form_for :building, html: {class: 'form-horizontal'} do |f| %>
	<div class="form-group">
		<%= f.label :label, {class: 'col-sm-2 control-label', for: 'buildingLabel' } %>
		<div class="col-sm-10">
			<%= f.text_field :label, {class: 'form-control', id: 'buildingLabel', placeholder: 'Enter Building Label'}%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :sublabel, {class: 'col-sm-2 control-label', for: 'buildingSubLabel' } %>
		<div class="col-sm-10">
			<%= f.text_field :sublabel, {class: 'form-control', id: 'buildingSubLabel', placeholder: 'Enter Building Sub-Label'} %>
		</div>
	</div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    	<%= f.submit "Save Building", {class: 'btn btn-primary'} %>
    </div>
  </div>
<% end %>

app/views/admin/buildings/index.html.erb
<div class="row">
	<% @buildings.each do |building| %>
	<div class="col-xs-6 col-md-3 admin-building-map">
		<strong><%= building.label %></strong><br />
		<a href="<%= url_for(edit_admin_building_path(:id => building.id)) %>">
		<%= image_tag "dul-libraries-profile-google-earth-#{building.name}-ground-level-#{building.image_width}x#{building.image_height}.jpg", 
									alt: "Profile of the #{building.label}",
									class: "img-responsive img-thumbnail"
									%>
		</a>									
	</div>
	<% end %>
</div>
<a href="<%= url_for(new_admin_building_path) %>" class="btn btn-primary btn-lg">Create New Building Entry</a>
<hr />
<table class="table">
	<thead>
		<tr>
			<th>Label</th>
			<th>Sub-Label</th>
			<th># Floors</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @buildings.each do |building| %>
		<tr>
			<td width="200"><%=building.label %></td>
			<td><%=building.sublabel %></td>
			<td><span class="badge"><%=building.floorplans.length %></span></td>
			<td><%= link_to h("Edit"), edit_admin_building_path(:id => building.id), :class => ['btn','btn-default','btn-sm'] %></td>
		</tr>
		<% end %>
	</tbody>
</table>