config/routes.rb
Rails.application.routes.draw do

  get 'floorplans/view'
  resources :floorplans
  
  resources :rooms
	resources :buildings

  get 'welcome/index'
	get 'welcome/about', :as => :about_this_site

  root 'welcome#index'

  get '/floorplans/:floorplan_name' => 'floorplans#show', :as => :floorplan_by_name 
  

  get 'admin' => 'admin#index'

  namespace :admin do
    get 'admin/index'
		get 'rooms/floorplan_filter_options' => 'rooms#floorplan_filter_options'
    resources :buildings
    resources :floorplans do
      post 'add_floor_area' => 'floorplans#add_floor_area'
			post 'update_floor_area/:floor_area_id' => 'floorplans#update_floor_area', :as => 'update_floor_area'
    end
		resources :floor_areas
    resources :rooms do
      post 'add_room_area' => 'rooms#add_room_area'
			post 'update_room_area' => 'rooms#update_room_area'
    end
    resources :rooms
		resources :room_areas
		resources :floorplan_maps
  end
  
  get "/support" => redirect("http://library.duke.edu/support"), :as => :support_home
  get "/featured-story" => redirect("http://library.duke.edu/support/crazy-smart"), :as => :featured_story
  get "/giving-opportunities" => redirect("http://library.duke.edu/support/giving-opportunities"), :as => :giving_opportunities
  get "/friends" => redirect("http://library.duke.edu/support/friends"), :as => :friends_of_libraries
  get "/news" => redirect("http://blogs.library.duke.edu"), :as => :news_and_events
  get "/how-to-give" => redirect("http://library.duke.edu/support/how-give"), :as => :how_to_give
  get "/give-now" => redirect("https://www.gifts.duke.edu/library"), :as => :give_now
  get "/contact" => redirect("http://library.duke.edu/support/contact"), :as => :contact
end

app/models/floorplan.rb
class Floorplan < ActiveRecord::Base
  require 'rmagick'
  include FloorplanMapImagery
  
  belongs_to :building
  belongs_to :floorplan_map
  has_many   :rooms, dependent: :destroy
  has_many   :floor_areas, dependent: :destroy
  
  attr_accessor :full_size_image
  attr_reader   :default_image_info
  
  scope :in_building, -> building {
    joins(:building).
    where('buildings.name = ?', building)
  }
  
  after_initialize :init
  def init
  end
  
  @@STUDY_CARRELS_ID_SUBSTRING = 'study_carrels'
  
  # http://stackoverflow.com/questions/11636541/use-a-scope-by-default-on-a-rails-has-many-relationship
  scope :below_ground, -> { where('label LIKE ?', 'Lower%').order('label ASC') }
  scope :above_ground, -> { where('label LIKE ?', 'Floor%').order('label ASC') }
  
  def Floorplan.STUDY_CARRELS_ID_SUBSTRING
    return @@STUDY_CARRELS_ID_SUBSTRING
  end
  
  def initialize_image_info
    # tip from:
    # http://stackoverflow.com/questions/16266933/rmagick-how-do-i-find-out-the-pixel-dimension-of-an-image
    @default_image_info = nil
    if !self.floorplan_map.nil?
      image_path = Rails.root.join 'app/assets/media/', self.floorplan_map.image_url
      @full_size_image = Magick::Image::read(image_path.to_s()).first
      @default_image_info = self.default_image(highlighted_rooms: [], render_as_nameable: true)
    end
  end
  
  def default_size
    return 'map_image_%s_max_width' % Rails.application.config.floorplan.default_map_max_width.to_s()
  end
  
  def default_image_size
    max_width_divisor = @full_size_image.columns.to_i() / Rails.application.config.floorplan.default_map_max_width.to_i()
    return self.resized_image(divisor = max_width_divisor)
  end
  
  def default_image(opts = {})
    defaults = {
      :highlighted_rooms => [],
      :render_as_nameable => true,
    }
    opts = defaults.merge(opts)  
    
    # scale the full size image to height = 100px
    if opts[:highlighted_rooms].empty?
      opts[:highlighted_rooms] = self.rooms.where(naming_opportunity: true)
    end
    scale_factor = Rails.application.config.floorplan.default_map_max_width.to_f() / @full_size_image.columns.to_f()
    rz = resized_map_image_metadata self.name, opts[:highlighted_rooms], @full_size_image,
        render_as_nameable: opts[:render_as_nameable], scale_factor: scale_factor, write: true, clobber: false
    
    return rz
  end
  
  def thumbnail_image(opts = {})
    defaults = {
      :highlighted_rooms => [],
      :render_as_nameable => true,
    }
    opts = defaults.merge(opts)
    
    # scale the full size image to height = 100px
    if opts[:highlighted_rooms].empty?
      opts[:highlighted_rooms] = self.rooms
    end
    scale_factor = Rails.application.config.floorplan.thumbnail_max_height.to_f() / @full_size_image.rows.to_f()
    rz = resized_map_image_metadata self.name, opts[:highlighted_rooms], @full_size_image,
        render_as_nameable: opts[:render_as_nameable], scale_factor: scale_factor, write: true, clobber: true, map_name_snippet: '_thumbnail_'

    return rz
  end
  
  def resized_image_size
    divisor = @full_size_image.columns.to_i() / Rails.application.config.floorplan.default_map_max_width.to_i()
    scale_factor = Rails.application.config.floorplan.default_map_max_width.to_f() / @full_size_image.columns.to_f()
    resized_image_width = (@full_size_image.columns / divisor).floor
    resized_image_height = (@full_size_image.rows / divisor).floor    
    
    return {
      :scale_factor => resized_image_width.to_f() / @full_size_image.columns.to_f(),
      :width => resized_image_width,
      :height => resized_image_height,
    }
  end
    
  def adjusted_roomarea_coordinates(coord)
    scale_factor = @default_image_info[:scale_factor]
    
    coords = coord.split(',')
    coords.map! { |n| n = (n.to_i() * scale_factor).to_i() }
    return coords.join(',')
  end
end

app/controllers/admin/floorplans_controller.rb
class Admin::FloorplansController < AdminController
  add_breadcrumb 'Floorplans', 'admin_floorplans_path'
  layout "colorbox", only: [:add_floor_area]
  
  def index
    # admin/floorplans
    #set_active_admin_sidebar 'Floorplan'
    @floorplans = Floorplan
      .joins(:building)
      .paginate(:page => params[:page], :per_page => 10)
      .all.order('buildings.label, label')
  end
  
  def edit
    # admin/floorplans/:id
    @floorplan = Floorplan.find(params[:id])
    @area_shapes = [['Polygon', 'poly'], ['Rectangle', 'rect'], ['Circle', 'circle']]
    add_breadcrumb "%s - %s" % [@floorplan.building.label, @floorplan.label]
  end
  
  def new
    # admin/floorplans/new
    @floorplan = Floorplan.new
    @area_shapes = [['Polygon', 'poly'], ['Rectangle', 'rect'], ['Circle', 'circle']]
    add_breadcrumb "New Floorplan"
  end
  
  def create
    @floorplan = Floorplan.new(floorplan_params)
    
    if @floorplan.save
      redirect_to edit_admin_floorplan_url(@floorplan)
    else
      render 'new'
    end
  end
  
  def update
    @floorplan = Floorplan.find(params[:id])
    
    if @floorplan.update(room_params)
      redirect_to edit_admin_floorplan_url(@floorplan)
    else
      render 'edit'
    end
  end
  
  def add_floor_area
    @floorplan = Floorplan.find(params[:floorplan_id])
    floor_area = FloorArea.new
    floor_area.coord = params[:coord]
    floor_area.shape = params[:shape]
    floor_area.floorplan = @floorplan
    
    if floor_area.save
      render template: 'admin/floorplans/_floorarea_row', :locals => {:floor_area => floor_area}
    else
      render json: ["An error occured while attempting to add this Floor Area."]
    end
  end
  
  private
    def floorplan_params
      params.require(:floorplan).permit(:label, :name, :sublabel)
    end
end

app/controllers/floorplans_controller.rb
class FloorplansController < ApplicationController
  include BuildingList
  include RoomsExtraSauce
  
  #caches_action :show, :layout => false, :expires_in => 1.hour
  caches_action :show, :show_by_name
  
  def view
  end
  
  def show_by_name
      
  end
  
  def show
    title = nil
    
    # TODO building list
    @floorplan_rooms_dict = {}
    @floorplan_building = ''
    
    rooms_aggregate = RoomsAggregate.new :named_spaces => {:label => 'Named Spaces'}, 
      :available_spaces_5000 => {:label => '$5,000 - $99,999', :min => 5000, :max => 99999},
      :available_spaces_100000 => {:label => '$100,000 - $500,000', :min => 100000, :max => 500000},
      :available_spaces_500000 => {:label => 'More than $500,000', :min => 500001}
    
    @floorplan = nil
    if params.has_key? :id
      @floorplan = Floorplan.find(params[:id])
    else
      @floorplan = Floorplan.find_by(name: params[:floorplan_name])
    end
    
    # initialize the image 'magick'
    @floorplan.initialize_image_info
    
    @building_list = build_building_list()

    # I believe it's time to re-think how to organize the 
    # list of rooms.
    # a) simply get all of them
    # b) parse through the entire list and handle the 
    #    cases where a room label spans multiple room areas
    @floorplan.rooms.where(naming_opportunity: true).order(:dollar_amount, :label).each do |room|
      rooms_aggregate.process_room(room)
    end
    @room_labels = rooms_aggregate.room_labels
    
    @named_spaces = @room_labels.select {|label, d| d[:category] == :named_spaces}.sort_by { |label, d| label }
    @available_5000 = @room_labels.select {|label, d| d[:category] == :available_spaces_5000}
    @available_100000 = @room_labels.select {|label, d| d[:category] == :available_spaces_100000}
    @available_500000 = @room_labels.select {|label, d| d[:category] == :available_spaces_500000}

    ##add_breadcrumb @floorplan.building.label, '#'
    add_breadcrumb "%s - %s" % [@floorplan.building.label, @floorplan.label]
    @floorplan_building = @floorplan.building.label
    @building_floorplans = @floorplan.building.floorplans
    @floorplan_default_image_info = @floorplan.default_image_info

  end
end

app/helpers/floorplans_helper.rb
module FloorplansHelper
end

app/views/admin/floorplans/_floorarea_row.html.erb
<tr id="floor_area_id-<%=floor_area.id%>">
	<td>
		<div class="row">
			<div class="col-xs-7"><input disabled class="form-control coord input-sm" type="text" value="<%=floor_area.coord %>"></div>
		</div>
	</td>
	<td><%= floor_area.shape %></td>
	<td>
		<button type="button" 
						class="btn btn-default btn-sm" 
						data-toggle="modal" 
						data-target="#diagInlineEditFloorArea" data-coord="<%=floor_area.coord %>" data-shape="<%= floor_area.shape %>"
						data-floor-area-id="<%=floor_area.id %>"
						data-url="<%= admin_floor_area_path(:id => floor_area.id) %>">
			<span class="glyphicon glyphicon-pencil" aria-hidden="true">			
		</button>		
		<button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash" aria-hidden="true"></button>		
	</td>
</tr>

app/views/admin/floorplans/_inline_form.html.erb
<div class="modal fade" role="dialog" id="diagInlineEditFloorArea" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
      <div class="modal-body">
        <form class="form">
				  <div class="form-group">
				    <label for="editFloorAreaCoord">Coordinates</label>
				    <textarea class="form-control input-sm" rows="4" name="coord" id="editFloorAreaCoord"></textarea>
				  </div>
				  <div class="form-group">
				    <label for="editFloorAreaShape">Shape</label>
				    <%= select_tag(:shape, options_for_select(@area_shapes), {class: 'form-control input-sm', id: 'editFloorAreaShape' }) %>
				  </div>
				  <input type="hidden" class="paramAreaId" id="editFloorAreaId" />
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" id="primaryButton" data-floor-area-id="" class="btn btn-primary" data-url="">Save Changes</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
		</div>
	</div>
</div>

app/views/admin/floorplans/edit.html.erb
<h3>Edit <%= @floorplan.building.label %> - <%= @floorplan.label %></h3>
<ul class="nav nav-tabs floorplan-tabs">
	<li role="presentation" class="active"><a data-toggle="tab" href="#floorplan-data">Info</a></li>
	<li role="presentation"><a data-toggle="tab" href="#floorareas">Floor Areas</a></li>
	<li role="presentation"><a data-toggle="tab" href="#rooms">Rooms</a></li>
</ul>
<div class="tab-content">
	<div id="floorplan-data" class="tab-pane fade in active">
		<%= form_for :floorplan, html: {class: 'form-horizontal'} do |f| %>
			<div class="form-group">
				<%= f.label :name, {class: 'col-sm-2 control-label', for: 'floorplanId' } %>
				<div class="col-sm-6">
					<%= f.text_field :name, {class: 'form-control input-sm', id: 'floorplanId', placeholder: 'Enter Floorplan Name'}%>
					<p class="help-block small">HTML-safe id string that identifies this floorplan (e.g. "p28_floor1")</p>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :label, {class: 'col-sm-2 control-label', for: 'floorplanLabel' } %>
				<div class="col-sm-10">
					<%= f.text_field :label, {class: 'form-control input-sm', id: 'floorplanLabel', placeholder: 'Enter Floorplan Label'}%>
					<p class="help-block small">The visible name/label for this floorplan, usually omitting the building label (e.g. "First Floor")</p>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :sublabel, {class: 'col-sm-2 control-label', for: 'floorplanSubLabel' } %>
				<div class="col-sm-10">
					<%= f.text_field :sublabel, {class: 'form-control input-sm', id: 'floorplanSubLabel', placeholder: 'Enter Floorplan Sub-Label'} %>
					<p class="help-block small">Optional subtitle for special circumstances (i.e. donor names)</p>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :building_id, {class: 'col-sm-2 control-label', for: 'floorplanBuilding' } %>
				<div class="col-sm-10">
					<%= f.collection_select :building_id, Building.all, :id, :label, {}, {class: 'form-control input-sm', id: 'floorplanBuilding' } %>
					<p class="help-block small">Choose the building for this floorplan.</p>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :floorplan_map_id, {class: 'col-sm-2 control-label', for: 'floorplanMap' } %>
				<div class="col-sm-10">
					<div class="row">
						<div class="col-xs-5">
						<%= f.collection_select :floorplan_map_id, FloorplanMap.all, :id, :label, {}, {class: 'form-control input-sm', id: 'floorplanMap' } %>
						</div>
					</div>
					<p class="help-block small">Select a master floorplan map (mainly used to correlate with HTML map areas).</p>
				</div>
			</div>
		  <div class="form-group">
		    <div class="col-sm-offset-2 col-sm-10">
		    	<%= f.submit "Save Floorplan", {class: 'btn btn-primary'} %>
		    </div>
		  </div>
		<% end %>
	</div>
	<div id="floorareas" class="tab-pane fade">
		<div class="panel panel-default">
			<div class="panel-heading">Floor Areas</div>
			<div class="panel-body">
			<table class="table">
				<thead>
					<tr>
						<th>Coordinates</th>
						<th>Shape</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody class="tbodyFloorAreas">
					<% @floorplan.floor_areas.each do |floor_area| %>
					<%= render partial: 'floorarea_row', locals: {floor_area: floor_area, floorplan: @floorplan} %>
					<% end %>
				</tbody>
				<thead>
					<tr>
						<th colspan="3"><strong>Add New Area</strong></th>
					</tr>
				</thead>					
				<tbody>
					<tr>
						<td>
							<div class="row">
								<div class="col-xs-5">
								<input id="newAreaCoords" class="form-control input-sm" type="text" placeholder="Add new coordinates"/>
								</div>
							</div>
						</td>
						<td>
							<div class="row">
								<div class="col-xs-7">
								<%= select_tag(:area_shape, options_for_select(@area_shapes), {class: 'form-control input-sm', id: 'areaMapShape' }) %>
								</div>
							</div>
						</td>
						<td>
							<%= link_to "Add Area", admin_floorplan_add_floor_area_path(:floorplan_id => @floorplan.id), 
							:class => ['btn','btn-default','btn-sm'], :id => 'btnAddFloorArea'%>
						</td>
					</tr>
				</tbody>
			</table>
			</div>
		</div>	
	</div>
	<div id="rooms" class="tab-pane fade">
		<table class="table table-condensed table-hover">
			<thead>
				<tr class="small">
					<th>Name</th>
					<th class="text-center">Naming<br />Opportunity?</th>
					<th class="text-center">Nameable?</th>
					<th class="text-center">Dollar Amount</th>
					<th class="text-center">Pending?</th>
					<th class="text-center">Carrel?</th>
				</tr>
			</thead>
			<tbody>
				<% @floorplan.rooms.each do |room| %>
				<tr class="small">
					<td><%= room.label %></td>
					<td class="text-center"><%= room.naming_opportunity? ? "Y" : "N" %></td>
					<td class="text-center"><%= room.nameable? ? "Y" : "N" %></td>
					<td class="text-right"><%= room.nameable? ? "$ %s" % number_with_delimiter(room.dollar_amount) : "-" %></td>
					<td class="text-center"><%= room.pending_sale? ? "Y" : "N" %></td>
					<td class="text-center"><%= room.carrel? ? "Y" : "N" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<!-- inline form -->
<%= render "inline_form" %>

app/views/admin/floorplans/index.html.erb
<a href="<%= url_for(new_admin_floorplan_path) %>" class="btn btn-primary btn-lg">Create New Floorplan Entry</a>
<hr />
<table class="table table-condensed">
	<thead>
		<tr>
			<th>Label</th>
			<th>Building</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @floorplans.each do |floorplan| %>
		<tr>
			<td>
				<%=floorplan.label %>
				<% if !floorplan.sublabel.nil? %>
				<br />
				<small><%=floorplan.sublabel %></small>
				<% end %>
			</td>
			<td><%=floorplan.building.label %></td>
			<td>
				<%= link_to h("Edit"), edit_admin_floorplan_path(:id => floorplan.id), :class => ['btn','btn-default','btn-sm'] %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<nav>
	<%= will_paginate @floorplans, renderer: BootstrapPagination::Rails, :class => 'pagination pagination-sm' %>
</nav>

app/views/admin/floorplans/new.html.erb
<h3>New Floorplan Entry</h3>
	
<%= form_for :floorplan, html: {class: 'form-horizontal'} do |f| %>
	<div class="form-group">
		<%= f.label :name, {class: 'col-sm-2 control-label', for: 'floorplanId' } %>
		<div class="col-sm-6">
			<%= f.text_field :name, {class: 'form-control input-sm', id: 'floorplanId', placeholder: 'Enter Floorplan Name'}%>
			<p class="help-block small">HTML-safe id string that identifies this floorplan (e.g. "p28_floor1")</p>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :label, {class: 'col-sm-2 control-label', for: 'floorplanLabel' } %>
		<div class="col-sm-10">
			<%= f.text_field :label, {class: 'form-control input-sm', id: 'floorplanLabel', placeholder: 'Enter Floorplan Label'}%>
			<p class="help-block small">The visible name/label for this floorplan, usually omitting the building label (e.g. "First Floor")</p>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :sublabel, {class: 'col-sm-2 control-label', for: 'floorplanSubLabel' } %>
		<div class="col-sm-10">
			<%= f.text_field :sublabel, {class: 'form-control input-sm', id: 'floorplanSubLabel', placeholder: 'Enter Floorplan Sub-Label'} %>
			<p class="help-block small">Optional subtitle for special circumstances (i.e. donor names)</p>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :building_id, {class: 'col-sm-2 control-label', for: 'floorplanBuilding' } %>
		<div class="col-sm-10">
			<%= f.collection_select :building_id, Building.all, :id, :label, {}, {class: 'form-control input-sm', id: 'floorplanBuilding' } %>
			<p class="help-block small">Choose the building for this floorplan.</p>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :floorplan_map_id, {class: 'col-sm-2 control-label', for: 'floorplanMap' } %>
		<div class="col-sm-10">
			<div class="row">
				<div class="col-xs-5">
				<%= f.collection_select :floorplan_map_id, FloorplanMap.all, :id, :label, {}, {class: 'form-control input-sm', id: 'floorplanMap' } %>
				</div>
			</div>
			<p class="help-block small">Select a master floorplan map (mainly used to correlate with HTML map areas).</p>
		</div>
	</div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    	<%= f.submit "Save Floorplan", {class: 'btn btn-primary'} %>
    </div>
  </div>
<% end %>